// Generated by gencpp from file first_project/secotor_times.msg
// DO NOT EDIT!


#ifndef FIRST_PROJECT_MESSAGE_SECOTOR_TIMES_H
#define FIRST_PROJECT_MESSAGE_SECOTOR_TIMES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first_project
{
template <class ContainerAllocator>
struct secotor_times_
{
  typedef secotor_times_<ContainerAllocator> Type;

  secotor_times_()
    : current_sector(0)
    , current_sector_time(0.0)
    , current_sector_mean_speed(0.0)  {
    }
  secotor_times_(const ContainerAllocator& _alloc)
    : current_sector(0)
    , current_sector_time(0.0)
    , current_sector_mean_speed(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _current_sector_type;
  _current_sector_type current_sector;

   typedef float _current_sector_time_type;
  _current_sector_time_type current_sector_time;

   typedef float _current_sector_mean_speed_type;
  _current_sector_mean_speed_type current_sector_mean_speed;





  typedef boost::shared_ptr< ::first_project::secotor_times_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first_project::secotor_times_<ContainerAllocator> const> ConstPtr;

}; // struct secotor_times_

typedef ::first_project::secotor_times_<std::allocator<void> > secotor_times;

typedef boost::shared_ptr< ::first_project::secotor_times > secotor_timesPtr;
typedef boost::shared_ptr< ::first_project::secotor_times const> secotor_timesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first_project::secotor_times_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first_project::secotor_times_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::first_project::secotor_times_<ContainerAllocator1> & lhs, const ::first_project::secotor_times_<ContainerAllocator2> & rhs)
{
  return lhs.current_sector == rhs.current_sector &&
    lhs.current_sector_time == rhs.current_sector_time &&
    lhs.current_sector_mean_speed == rhs.current_sector_mean_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::first_project::secotor_times_<ContainerAllocator1> & lhs, const ::first_project::secotor_times_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace first_project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::first_project::secotor_times_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first_project::secotor_times_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_project::secotor_times_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_project::secotor_times_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_project::secotor_times_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_project::secotor_times_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first_project::secotor_times_<ContainerAllocator> >
{
  static const char* value()
  {
    return "245a0ea055f4366c2b43f7ea3395f4ec";
  }

  static const char* value(const ::first_project::secotor_times_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x245a0ea055f4366cULL;
  static const uint64_t static_value2 = 0x2b43f7ea3395f4ecULL;
};

template<class ContainerAllocator>
struct DataType< ::first_project::secotor_times_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first_project/secotor_times";
  }

  static const char* value(const ::first_project::secotor_times_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first_project::secotor_times_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 current_sector\n"
"float32 current_sector_time\n"
"float32 current_sector_mean_speed\n"
;
  }

  static const char* value(const ::first_project::secotor_times_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first_project::secotor_times_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_sector);
      stream.next(m.current_sector_time);
      stream.next(m.current_sector_mean_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct secotor_times_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first_project::secotor_times_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first_project::secotor_times_<ContainerAllocator>& v)
  {
    s << indent << "current_sector: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current_sector);
    s << indent << "current_sector_time: ";
    Printer<float>::stream(s, indent + "  ", v.current_sector_time);
    s << indent << "current_sector_mean_speed: ";
    Printer<float>::stream(s, indent + "  ", v.current_sector_mean_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_PROJECT_MESSAGE_SECOTOR_TIMES_H
